### ISSUE TITLE
Unable to send from kusama to basilisk

### ISSUE THREAD

**Issue by daiagi** [paraspell/xcm-sdk#40]
Have issue when trying to send from Kusama to Basilisk
work well when sending from Kusama to Statemine
please advice

this code:
```ts
    const promise = paraspell.Builder(apiKusama)
    .to('Basilisk')
    .amount(amountValue)
    .address(toAddress.value)
    .build()


    promise
      .signAndSend(
        fromAddress.value,
        { signer: injector.signer },
        transactionHandler
      )
      .catch(errorHandler)
```

Throws error:

```

TypeError: Cannot read properties of undefined (reading 'relayChainAssetSymbol')
    at getRelayChainSymbol (index.mjs:4631:1)
    at createHeaderPolkadotXCM (index.mjs:5212:1)
    at transferRelayToPara (index.mjs:5303:1)
    at RelayToParaBuilder.build (index.mjs:5351:1)
    at _callee3$ (VM463161 Teleport.vue:48:465)
    at c (widget.js:1:2206)
    at Generator._invoke (widget.js:1:1959)
    at Generator.next (widget.js:1:2569)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)

```

Sending to ```Statemine``` works well

same issue if i use ```xcmPallet.transferRelayToPara``` syntax

**Comment by dudo50** [comment]
This issue was resolved and PR merged. Thanks once again for your contribution. Closing this issue.
